ni -D @astrojs/markdown-remark
- this seem to be some kind of pnpm issue, because astro already depends
  on @astrojs/markdown-remark
- otherwise it show this error:
```
error   Cannot find module '@astrojs/markdown-remark/ssr-utils' imported from './jlarky-blog/src/pages/posts/next-js-impressions.md'
```